sonar.projectKey=MyNotes
sonar.projectName=MyNotes
sonar.projectVersion=1.0

sonar.sources=backend,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000